INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0001', 'novel', 25.990, 'The Lost City', 1);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0002', 'historical', 19.950, 'Ancient Chronicles', 2);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0003', 'for kids', 12.500, 'Adventure in Wonderland', 3);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0004', 'poems', 15.750, 'Whispers of the Heart', 4);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0005', 'crime story', 30.500, 'Midnight Shadows', 5);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0006', 'science fiction', 22.990, 'Galactic Odyssey', 6);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0007', 'science', 18.750, 'The Quantum Universe', 3);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0008', 'novel', 27.500, 'Eternal Love', 8);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0009', 'historical', 21.950, 'The Silk Road', 9);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0010', 'for kids', 14.990, 'Magic Kingdom', 10);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0011', 'novel', 26.500, 'Beyond the Horizon', 1);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0012', 'poems', 14.250, 'Voices in the Wind', 3);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0013', 'science fiction', 23.750, 'Time Travelers', 3);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0014', 'crime story', 32.000, 'Underworld Secrets', 4);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0015', 'historical', 20.500, 'In the Shadows of Time', 5);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0016', 'novel', 28.750, 'Uncharted Destinies', 6);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0017', 'for kids', 16.990, 'Enchanted Forest', 2);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0018', 'science', 24.500, 'Exploring the Cosmos', 8);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0019', 'novel', 30.250, 'Infinite Dreams', 3);
INSERT INTO demo_test.Book (Book_Id, Type, Price, Title, Pub_Id) VALUES ('B0020', 'poems', 16.500, 'Silent Whispers', 6);
